<?php
/**
 * CustomerOrderDetailDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\Deposco
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deposco API
 *
 * Welcome to the Deposco API Reference! The Deposco API enables you to integrate your system with Deposco.  * Integrate a product information system (PIM) by creating and retrieving data for items, packs, UPCs, and kits. * Set up warehouse data by creating facilities, zones, locations, and storage details. * Create inbound orders that can be received and outbound orders that can be fulfilled with Deposco warehouse management processes.  This reference provides details on available operations, endpoints, parameters, schemas, and responses.  Example requests and responses are also available for you to use as a reference. You can copy the examples to use as a starting point for your own requests.  Review the guides to learn how the API is used in common business scenarios such as setting up the warehouse and integrating a Product Information Management (PIM) system.  When you're ready to get started, register for a developer account and then log in to create your application in the developer portal.
 *
 * The version of the OpenAPI document: 2.0.2519
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BeLenka\Deposco\Model;

use \ArrayAccess;
use \BeLenka\Deposco\ObjectSerializer;

/**
 * CustomerOrderDetailDTO Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\Deposco
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CustomerOrderDetailDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CustomerOrderDetailDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'co_payment_terms' => '\BeLenka\Deposco\Model\CustomerOrderPaymentTermDTO[]',
        'co_payments' => '\BeLenka\Deposco\Model\CustomerOrderPaymentDTO[]',
        'co_charge_allowances' => '\BeLenka\Deposco\Model\CustomerOrderChargeAllowanceDTO[]',
        'co_taxes' => '\BeLenka\Deposco\Model\CustomerOrderTaxDTO[]',
        'co_refunds' => '\BeLenka\Deposco\Model\CustomerOrderRefundDTO[]',
        'co_references' => '\BeLenka\Deposco\Model\CustomerOrderReferenceDTO[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'co_payment_terms' => null,
        'co_payments' => null,
        'co_charge_allowances' => null,
        'co_taxes' => null,
        'co_refunds' => null,
        'co_references' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'co_payment_terms' => true,
        'co_payments' => true,
        'co_charge_allowances' => true,
        'co_taxes' => true,
        'co_refunds' => true,
        'co_references' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'co_payment_terms' => 'coPaymentTerms',
        'co_payments' => 'coPayments',
        'co_charge_allowances' => 'coChargeAllowances',
        'co_taxes' => 'coTaxes',
        'co_refunds' => 'coRefunds',
        'co_references' => 'coReferences'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'co_payment_terms' => 'setCoPaymentTerms',
        'co_payments' => 'setCoPayments',
        'co_charge_allowances' => 'setCoChargeAllowances',
        'co_taxes' => 'setCoTaxes',
        'co_refunds' => 'setCoRefunds',
        'co_references' => 'setCoReferences'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'co_payment_terms' => 'getCoPaymentTerms',
        'co_payments' => 'getCoPayments',
        'co_charge_allowances' => 'getCoChargeAllowances',
        'co_taxes' => 'getCoTaxes',
        'co_refunds' => 'getCoRefunds',
        'co_references' => 'getCoReferences'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('co_payment_terms', $data ?? [], null);
        $this->setIfExists('co_payments', $data ?? [], null);
        $this->setIfExists('co_charge_allowances', $data ?? [], null);
        $this->setIfExists('co_taxes', $data ?? [], null);
        $this->setIfExists('co_refunds', $data ?? [], null);
        $this->setIfExists('co_references', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets co_payment_terms
     *
     * @return \BeLenka\Deposco\Model\CustomerOrderPaymentTermDTO[]|null
     */
    public function getCoPaymentTerms()
    {
        return $this->container['co_payment_terms'];
    }

    /**
     * Sets co_payment_terms
     *
     * @param \BeLenka\Deposco\Model\CustomerOrderPaymentTermDTO[]|null $co_payment_terms Array of payment terms for the customer order.
     *
     * @return self
     */
    public function setCoPaymentTerms($co_payment_terms)
    {
        if (is_null($co_payment_terms)) {
            array_push($this->openAPINullablesSetToNull, 'co_payment_terms');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('co_payment_terms', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['co_payment_terms'] = $co_payment_terms;

        return $this;
    }

    /**
     * Gets co_payments
     *
     * @return \BeLenka\Deposco\Model\CustomerOrderPaymentDTO[]|null
     */
    public function getCoPayments()
    {
        return $this->container['co_payments'];
    }

    /**
     * Sets co_payments
     *
     * @param \BeLenka\Deposco\Model\CustomerOrderPaymentDTO[]|null $co_payments Array of payments for the customer order.
     *
     * @return self
     */
    public function setCoPayments($co_payments)
    {
        if (is_null($co_payments)) {
            array_push($this->openAPINullablesSetToNull, 'co_payments');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('co_payments', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['co_payments'] = $co_payments;

        return $this;
    }

    /**
     * Gets co_charge_allowances
     *
     * @return \BeLenka\Deposco\Model\CustomerOrderChargeAllowanceDTO[]|null
     */
    public function getCoChargeAllowances()
    {
        return $this->container['co_charge_allowances'];
    }

    /**
     * Sets co_charge_allowances
     *
     * @param \BeLenka\Deposco\Model\CustomerOrderChargeAllowanceDTO[]|null $co_charge_allowances Array of charge allowances for the customer order.
     *
     * @return self
     */
    public function setCoChargeAllowances($co_charge_allowances)
    {
        if (is_null($co_charge_allowances)) {
            array_push($this->openAPINullablesSetToNull, 'co_charge_allowances');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('co_charge_allowances', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['co_charge_allowances'] = $co_charge_allowances;

        return $this;
    }

    /**
     * Gets co_taxes
     *
     * @return \BeLenka\Deposco\Model\CustomerOrderTaxDTO[]|null
     */
    public function getCoTaxes()
    {
        return $this->container['co_taxes'];
    }

    /**
     * Sets co_taxes
     *
     * @param \BeLenka\Deposco\Model\CustomerOrderTaxDTO[]|null $co_taxes Array of taxes for the customer order.
     *
     * @return self
     */
    public function setCoTaxes($co_taxes)
    {
        if (is_null($co_taxes)) {
            array_push($this->openAPINullablesSetToNull, 'co_taxes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('co_taxes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['co_taxes'] = $co_taxes;

        return $this;
    }

    /**
     * Gets co_refunds
     *
     * @return \BeLenka\Deposco\Model\CustomerOrderRefundDTO[]|null
     */
    public function getCoRefunds()
    {
        return $this->container['co_refunds'];
    }

    /**
     * Sets co_refunds
     *
     * @param \BeLenka\Deposco\Model\CustomerOrderRefundDTO[]|null $co_refunds Array of refunds for the customer order.
     *
     * @return self
     */
    public function setCoRefunds($co_refunds)
    {
        if (is_null($co_refunds)) {
            array_push($this->openAPINullablesSetToNull, 'co_refunds');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('co_refunds', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['co_refunds'] = $co_refunds;

        return $this;
    }

    /**
     * Gets co_references
     *
     * @return \BeLenka\Deposco\Model\CustomerOrderReferenceDTO[]|null
     */
    public function getCoReferences()
    {
        return $this->container['co_references'];
    }

    /**
     * Sets co_references
     *
     * @param \BeLenka\Deposco\Model\CustomerOrderReferenceDTO[]|null $co_references Array of reference values for the customer order.
     *
     * @return self
     */
    public function setCoReferences($co_references)
    {
        if (is_null($co_references)) {
            array_push($this->openAPINullablesSetToNull, 'co_references');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('co_references', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['co_references'] = $co_references;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


